import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Debt, DemoStore, dateLabel, debtBalance, debtStatus, downloadCsv, money } from '../data/demo-store';
import { Icon } from '../shared/icon';

const blankDebt = (): Debt => ({ id: '', party: '', phone: '', kind: 'Por cobrar', total: 0, paid: 0, date: '2026-09-22', dueDate: '', notes: '' });

@Component({selector:'app-debts',standalone:true,imports:[FormsModule,Icon],template:`
  <div class="page-header"><div><div class="eyebrow">CUENTAS PENDIENTES</div><h1>Deudas</h1><p>Administra las cuentas por cobrar de clientes y por pagar a proveedores.</p></div></div>
  <section class="card summary-card"><div class="card-heading"><h2>Resumen de saldos</h2><span class="period-pill">En tiempo real · Demo</span></div><div class="summary-grid four"><div class="summary-item"><span>Por cobrar</span><strong>{{money(receivable())}}</strong><small>Saldo de clientes</small></div><div class="summary-item"><span>Por pagar</span><strong>{{money(payable())}}</strong><small>Saldo a proveedores</small></div><div class="summary-item"><span>Vencidas</span><strong>{{overdueCount()}}</strong><small>Requieren atención</small></div><div class="summary-item"><span>Pagadas</span><strong>{{paidCount()}}</strong><small>Cuentas cerradas</small></div></div></section>
  <section class="card table-card"><div class="card-heading table-heading"><div><h2>Registro de deudas</h2><p>{{filtered().length}} resultados</p></div><div class="card-actions">@if(store.role()==='admin'){<button class="btn btn-primary" (click)="openCreate()"><app-icon name="plus"/> Nueva deuda</button>}<select class="btn btn-outline filter-select" aria-label="Filtrar por tipo" [ngModel]="kindFilter()" (ngModelChange)="kindFilter.set($event);page.set(1)"><option value="">Todos los tipos</option><option>Por cobrar</option><option>Por pagar</option></select><select class="btn btn-outline filter-select" aria-label="Filtrar por estado" [ngModel]="statusFilter()" (ngModelChange)="statusFilter.set($event);page.set(1)"><option value="">Todos los estados</option><option>Pendiente</option><option>Parcial</option><option>Vencida</option><option>Pagada</option></select><button class="btn btn-outline" (click)="export()"><app-icon name="download"/><span class="hide-small">Descargar</span></button></div></div>
    <div class="table-scroll"><table><thead><tr><th>Persona o empresa</th><th>Tipo</th><th>Monto original</th><th>Pagado</th><th>Saldo</th><th>Vencimiento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@for(d of pageItems();track d.id){<tr><td><span class="table-primary">{{d.party}}</span><small class="table-sub">{{d.phone}} · {{d.id}}</small></td><td>{{d.kind}}</td><td>{{money(d.total)}}</td><td>{{money(d.paid)}}</td><td><strong>{{money(balance(d))}}</strong></td><td>{{dateLabel(d.dueDate)}}</td><td><span class="status" [class.status-good]="status(d)==='Pagada'" [class.status-warn]="status(d)==='Parcial'||status(d)==='Pendiente'" [class.status-bad]="status(d)==='Vencida'">{{status(d)}}</span></td><td><div class="row-actions">@if(store.role()==='admin'){<button class="btn btn-outline" (click)="openEdit(d)"><app-icon name="edit"/> Editar</button><button class="btn btn-outline" [disabled]="balance(d)===0" (click)="openPayment(d)">Registrar pago</button>}</div></td></tr>} @empty {<tr><td colspan="8" class="empty-table">No encontramos deudas con ese criterio.</td></tr>}</tbody></table></div>
    <div class="table-footer"><button class="btn btn-outline" [disabled]="page()===1" (click)="page.update(n=>n-1)">Anterior</button><span>Página {{page()}} de {{pageCount()}}</span><button class="btn btn-outline" [disabled]="page()>=pageCount()" (click)="page.update(n=>n+1)">Siguiente</button></div>
  </section>

  @if(modalOpen()){<div class="modal-backdrop" (click)="closeForm()"><section class="modal-card" role="dialog" aria-modal="true" aria-label="Formulario de deuda" (click)="$event.stopPropagation()"><div class="modal-header"><div><div class="eyebrow">DEUDAS</div><h2>{{editingId() ? 'Editar deuda' : 'Nueva deuda'}}</h2></div><button class="icon-button" aria-label="Cerrar" (click)="closeForm()"><app-icon name="close"/></button></div><form class="modal-form" (ngSubmit)="save()"><div class="form-grid"><label class="field-label">Tipo de deuda<select class="field-input" name="kind" [(ngModel)]="draft.kind"><option>Por cobrar</option><option>Por pagar</option></select></label><label class="field-label">Persona o empresa<input class="field-input" name="party" [(ngModel)]="draft.party" required [placeholder]="draft.kind==='Por cobrar'?'Ej. Salón Renueva':'Ej. Select Hair Bolivia'" /></label><label class="field-label">Teléfono<input class="field-input" name="phone" [(ngModel)]="draft.phone" required placeholder="Ej. 70123456" /></label><label class="field-label">Monto original (Bs.)<input class="field-input" type="number" min="0.01" step="0.01" name="total" [(ngModel)]="draft.total" required /></label><label class="field-label">Monto pagado (Bs.)<input class="field-input" type="number" min="0" step="0.01" name="paid" [(ngModel)]="draft.paid" required /></label><label class="field-label">Fecha de registro<input class="field-input" type="date" name="date" [(ngModel)]="draft.date" required /></label><label class="field-label">Fecha de vencimiento<input class="field-input" type="date" name="dueDate" [(ngModel)]="draft.dueDate" required /></label><label class="field-label form-wide">Notas<textarea class="field-input field-textarea" name="notes" [(ngModel)]="draft.notes" placeholder="Detalle de la compra, venta o acuerdo de pago"></textarea></label></div>@if(error()){<p class="form-error">{{error()}}</p>}<div class="modal-actions"><button type="button" class="btn btn-outline" (click)="closeForm()">Cancelar</button><button type="submit" class="btn btn-primary">{{editingId() ? 'Guardar cambios' : 'Crear deuda'}}</button></div></form></section></div>}

  @if(paymentOpen() && selectedDebt();as d){<div class="modal-backdrop" (click)="closePayment()"><section class="modal-card small-modal" role="dialog" aria-modal="true" aria-label="Registrar pago" (click)="$event.stopPropagation()"><div class="modal-header"><div><div class="eyebrow">{{d.kind}}</div><h2>Registrar pago</h2></div><button class="icon-button" aria-label="Cerrar" (click)="closePayment()"><app-icon name="close"/></button></div><form class="modal-form" (ngSubmit)="applyPayment()"><p class="inline-hint"><strong>{{d.party}}</strong><br/>Saldo pendiente: {{money(balance(d))}}</p><label class="field-label">Monto del pago (Bs.)<input class="field-input" type="number" min="0.01" [max]="balance(d)" step="0.01" name="paymentAmount" [(ngModel)]="paymentAmount" required /></label>@if(paymentError()){<p class="form-error">{{paymentError()}}</p>}<div class="modal-actions"><button type="button" class="btn btn-outline" (click)="closePayment()">Cancelar</button><button type="submit" class="btn btn-primary">Aplicar pago</button></div></form></section></div>}
`})
export class Debts {
  readonly store=inject(DemoStore);readonly money=money;readonly dateLabel=dateLabel;readonly balance=debtBalance;readonly status=debtStatus;
  readonly page=signal(1);readonly kindFilter=signal('');readonly statusFilter=signal('');readonly modalOpen=signal(false);readonly editingId=signal('');readonly error=signal('');
  readonly paymentOpen=signal(false);readonly selectedDebt=signal<Debt|null>(null);readonly paymentError=signal('');paymentAmount=0;draft=blankDebt();
  readonly filtered=computed(()=>this.store.debts().filter(d=>`${d.party} ${d.phone} ${d.id} ${d.notes}`.toLowerCase().includes(this.store.query().toLowerCase())&&(!this.kindFilter()||d.kind===this.kindFilter())&&(!this.statusFilter()||debtStatus(d)===this.statusFilter())));
  readonly pageCount=computed(()=>Math.max(1,Math.ceil(this.filtered().length/7)));
  readonly pageItems=computed(()=>this.filtered().slice((Math.min(this.page(),this.pageCount())-1)*7,Math.min(this.page(),this.pageCount())*7));
  readonly receivable=computed(()=>this.store.debts().filter(d=>d.kind==='Por cobrar').reduce((sum,d)=>sum+debtBalance(d),0));
  readonly payable=computed(()=>this.store.debts().filter(d=>d.kind==='Por pagar').reduce((sum,d)=>sum+debtBalance(d),0));
  readonly overdueCount=computed(()=>this.store.debts().filter(d=>debtStatus(d)==='Vencida').length);
  readonly paidCount=computed(()=>this.store.debts().filter(d=>debtStatus(d)==='Pagada').length);
  openCreate(){this.draft=blankDebt();this.editingId.set('');this.error.set('');this.modalOpen.set(true);}
  openEdit(debt:Debt){this.draft={...debt};this.editingId.set(debt.id);this.error.set('');this.modalOpen.set(true);}
  closeForm(){this.modalOpen.set(false);}
  save(){
    if(!this.draft.party.trim()||!this.draft.phone.trim()||!this.draft.date||!this.draft.dueDate){this.error.set('Completa la persona o empresa, teléfono y fechas.');return;}
    if(this.draft.total<=0){this.error.set('El monto original debe ser mayor a cero.');return;}
    if(this.draft.paid<0||this.draft.paid>this.draft.total){this.error.set('El monto pagado debe estar entre cero y el monto original.');return;}
    if(this.editingId()) this.store.updateDebt({...this.draft,id:this.editingId()});
    else this.store.addDebt({...this.draft,id:`DEU-${String(this.store.debts().length+1).padStart(3,'0')}`});
    this.page.set(1);this.closeForm();
  }
  openPayment(debt:Debt){this.selectedDebt.set(debt);this.paymentAmount=0;this.paymentError.set('');this.paymentOpen.set(true);}
  closePayment(){this.paymentOpen.set(false);this.selectedDebt.set(null);}
  applyPayment(){const debt=this.selectedDebt();if(!debt)return;const pending=debtBalance(debt);if(this.paymentAmount<=0||this.paymentAmount>pending){this.paymentError.set(`Ingresa un monto mayor a cero y no superior a ${money(pending)}.`);return;}this.store.updateDebt({...debt,paid:debt.paid+this.paymentAmount});this.closePayment();}
  export(){downloadCsv('deudas-cabellos-vero.csv',['Código','Persona o empresa','Teléfono','Tipo','Monto original Bs.','Pagado Bs.','Saldo Bs.','Fecha','Vencimiento','Estado','Notas'],this.filtered().map(d=>[d.id,d.party,d.phone,d.kind,d.total,d.paid,debtBalance(d),d.date,d.dueDate,debtStatus(d),d.notes]));}
}
