import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DemoStore, Order, dateLabel, downloadCsv, money } from '../data/demo-store';
import { Icon } from '../shared/icon';

const blankOrder=():Order=>({id:'',product:'',supplier:'',quantity:1,unit:'unid.',value:0,delivery:'',status:'Pendiente'});
@Component({selector:'app-orders',standalone:true,imports:[FormsModule,Icon],template:`
  <div class="page-header"><div><div class="eyebrow">ABASTECIMIENTO</div><h1>Pedidos</h1><p>Da seguimiento a las compras de tu tienda.</p></div></div>
  <section class="card summary-card"><div class="card-heading"><h2>Resumen de pedidos</h2><span class="period-pill">En tiempo real · Demo</span></div><div class="summary-grid four"><div class="summary-item"><span>Total de pedidos</span><strong>{{store.orders().length}}</strong><small>Registrados</small></div><div class="summary-item"><span>Recibidos</span><strong>{{count('Recibido')}}</strong><small>Completados</small></div><div class="summary-item"><span>Pendientes</span><strong>{{count('Pendiente')+count('Confirmado')}}</strong><small>Por recibir</small></div><div class="summary-item"><span>Retrasados</span><strong>{{count('Retrasado')}}</strong><small>Requieren atención</small></div></div></section>
  <section class="card table-card"><div class="card-heading table-heading"><div><h2>Pedidos recientes</h2><p>{{filtered().length}} resultados</p></div><div class="card-actions">@if(store.role()==='admin'){<button class="btn btn-primary" (click)="open()"><app-icon name="plus"/> Nuevo pedido</button>}<select class="btn btn-outline filter-select" aria-label="Filtrar por estado" [ngModel]="statusFilter()" (ngModelChange)="statusFilter.set($event)"><option value="">Todos los estados</option><option>Pendiente</option><option>Confirmado</option><option>Recibido</option><option>Retrasado</option><option>Devuelto</option></select><button class="btn btn-outline" (click)="export()"><app-icon name="download"/><span class="hide-small">Descargar</span></button></div></div><div class="table-scroll"><table><thead><tr><th>Producto</th><th>Valor del pedido</th><th>Cantidad</th><th>N.º de pedido</th><th>Entrega prevista</th><th>Estado</th></tr></thead><tbody>@for(o of pageItems();track o.id){<tr><td><span class="table-primary">{{o.product}}</span><small class="table-sub">{{o.supplier}}</small></td><td>{{money(o.value)}}</td><td>{{o.quantity}} {{o.unit}}</td><td>{{o.id}}</td><td>{{dateLabel(o.delivery)}}</td><td><span class="status" [class.status-good]="o.status==='Recibido'" [class.status-warn]="o.status==='Retrasado'||o.status==='Pendiente'" [class.status-neutral]="o.status==='Confirmado'||o.status==='Devuelto'">{{o.status}}</span></td></tr>} @empty {<tr><td colspan="6" class="empty-table">No encontramos pedidos con ese criterio.</td></tr>}</tbody></table></div><div class="table-footer"><button class="btn btn-outline" [disabled]="page()===1" (click)="page.update(n=>n-1)">Anterior</button><span>Página {{page()}} de {{pageCount()}}</span><button class="btn btn-outline" [disabled]="page()>=pageCount()" (click)="page.update(n=>n+1)">Siguiente</button></div></section>
  @if(modalOpen()){<div class="modal-backdrop" (click)="modalOpen.set(false)"><section class="modal-card" role="dialog" aria-modal="true" aria-label="Nuevo pedido" (click)="$event.stopPropagation()"><div class="modal-header"><div><div class="eyebrow">ABASTECIMIENTO</div><h2>Nuevo pedido</h2></div><button class="icon-button" aria-label="Cerrar" (click)="modalOpen.set(false)"><app-icon name="close"/></button></div><form class="modal-form" (ngSubmit)="save()"><div class="form-grid"><label class="field-label">Producto<select class="field-input" name="product" [(ngModel)]="draft.product" (ngModelChange)="selectProduct()" required><option value="">Seleccionar producto</option>@for(p of store.products();track p.id){<option [value]="p.name">{{p.name}}</option>}</select></label><label class="field-label">Proveedor<select class="field-input" name="supplier" [(ngModel)]="draft.supplier" required><option value="">Seleccionar proveedor</option>@for(s of store.suppliers();track s.id){<option [value]="s.name">{{s.name}}</option>}</select></label><label class="field-label">Cantidad<input class="field-input" type="number" min="1" name="quantity" [(ngModel)]="draft.quantity" (ngModelChange)="updateValue()" required /></label><label class="field-label">Unidad<input class="field-input" name="unit" [(ngModel)]="draft.unit" required /></label><label class="field-label">Valor total (Bs.)<input class="field-input" type="number" min="0" name="value" [(ngModel)]="draft.value" required /></label><label class="field-label">Entrega prevista<input class="field-input" type="date" name="delivery" [(ngModel)]="draft.delivery" required /></label></div><label class="checkbox-line"><input type="checkbox" [(ngModel)]="notify" name="notify" /> Avisarme el día de la entrega</label>@if(error()){<p class="form-error">{{error()}}</p>}<div class="modal-actions"><button type="button" class="btn btn-outline" (click)="modalOpen.set(false)">Cancelar</button><button type="submit" class="btn btn-primary">Crear pedido</button></div></form></section></div>}
`})
export class Orders {
  readonly store=inject(DemoStore);readonly money=money;readonly dateLabel=dateLabel;readonly page=signal(1);readonly modalOpen=signal(false);readonly error=signal('');readonly statusFilter=signal('');draft=blankOrder();notify=true;
  readonly filtered=computed(()=>this.store.orders().filter(o=>`${o.product} ${o.id} ${o.supplier}`.toLowerCase().includes(this.store.query().toLowerCase())&&(!this.statusFilter()||o.status===this.statusFilter())));
  readonly pageCount=computed(()=>Math.max(1,Math.ceil(this.filtered().length/7)));
  readonly pageItems=computed(()=>this.filtered().slice((Math.min(this.page(),this.pageCount())-1)*7,Math.min(this.page(),this.pageCount())*7));
  count(status:Order['status']){return this.store.orders().filter(o=>o.status===status).length;}
  open(){this.draft=blankOrder();this.error.set('');this.modalOpen.set(true);}
  selectProduct(){const p=this.store.products().find(p=>p.name===this.draft.product);if(p){this.draft.supplier=p.supplier;this.draft.unit=p.unit;this.updateValue();}}
  updateValue(){const p=this.store.products().find(p=>p.name===this.draft.product);if(p)this.draft.value=p.price*this.draft.quantity;}
  save(){if(!this.draft.product||!this.draft.supplier||!this.draft.delivery||this.draft.quantity<1){this.error.set('Completa producto, proveedor, cantidad y fecha de entrega.');return;}this.store.addOrder({...this.draft,id:`PED-${1043+this.store.orders().length-5}`});this.page.set(1);this.modalOpen.set(false);}
  export(){downloadCsv('pedidos-cabellos-vero.csv',['N.º','Producto','Proveedor','Cantidad','Valor Bs.','Entrega','Estado'],this.filtered().map(o=>[o.id,o.product,o.supplier,o.quantity,o.value,o.delivery,o.status]));}
}
