import { Component, computed, inject, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { DemoStore, Product, dateLabel, downloadCsv, money, stockStatus } from '../data/demo-store';
import { Icon } from '../shared/icon';

@Component({ selector:'app-product-detail', standalone:true, imports:[RouterLink,FormsModule,Icon], template:`
  <div class="page-header"><div><a routerLink="/inventario" class="back-link">‹ Volver al inventario</a><h1>{{ product()?.name || 'Producto no encontrado' }}</h1><p>{{ product()?.id }} · {{ product()?.category }}</p></div></div>
  @if (product(); as p) { <section class="card detail-card"><div class="detail-heading"><div><h2>{{ p.name }}</h2><span class="status" [class.status-good]="stockStatus(p)==='Disponible'" [class.status-warn]="stockStatus(p)==='Stock bajo'" [class.status-bad]="stockStatus(p)==='Agotado'">{{ stockStatus(p) }}</span></div><div class="card-actions">@if (store.role()==='admin') { <button class="btn btn-outline" (click)="openEdit(p)"><app-icon name="edit"/> Editar</button> }<button class="btn btn-outline" (click)="download(p)"><app-icon name="download"/> Descargar</button></div></div>
    <div class="tabs"><button [class.selected]="tab()==='general'" (click)="tab.set('general')">Información general</button><button [class.selected]="tab()==='compras'" (click)="tab.set('compras')">Compras</button><button [class.selected]="tab()==='ajustes'" (click)="tab.set('ajustes')">Ajustes</button><button [class.selected]="tab()==='historial'" (click)="tab.set('historial')">Historial</button></div>
    @if (tab()==='general') { <div class="detail-grid"><div><h3>Datos principales</h3><dl class="detail-list"><div><dt>Nombre</dt><dd>{{ p.name }}</dd></div><div><dt>Código</dt><dd>{{ p.id }}</dd></div><div><dt>Categoría</dt><dd>{{ p.category }}</dd></div><div><dt>Precio de compra</dt><dd>{{ money(p.price) }}</dd></div><div><dt>Fecha de vencimiento</dt><dd>{{ dateLabel(p.expiry) }}</dd></div><div><dt>Stock mínimo</dt><dd>{{ p.threshold }} {{ p.unit }}</dd></div></dl><h3>Proveedor</h3><dl class="detail-list"><div><dt>Nombre</dt><dd>{{ p.supplier || 'Sin asignar' }}</dd></div><div><dt>Contacto</dt><dd>{{ supplierPhone(p.supplier) }}</dd></div></dl></div><div class="detail-side"><div class="product-visual"><span>{{ p.name[0] }}</span><small>Imagen del producto</small></div><div class="stock-facts"><div><span>Stock actual</span><strong>{{ p.quantity }} {{ p.unit }}</strong></div><div><span>Stock mínimo</span><strong>{{ p.threshold }} {{ p.unit }}</strong></div><div><span>Unidades vendidas</span><strong>{{ p.sold }}</strong></div><div><span>Valor en inventario</span><strong>{{ money(p.quantity*p.price) }}</strong></div></div></div></div> }
    @if (tab()==='compras') { <div class="tab-content"><h3>Compras relacionadas</h3><div class="table-scroll"><table><thead><tr><th>Pedido</th><th>Proveedor</th><th>Cantidad</th><th>Fecha esperada</th><th>Estado</th></tr></thead><tbody>@for (o of relatedOrders(); track o.id) { <tr><td>{{ o.id }}</td><td>{{ o.supplier }}</td><td>{{ o.quantity }} {{ o.unit }}</td><td>{{ dateLabel(o.delivery) }}</td><td><span class="status">{{ o.status }}</span></td></tr> } @empty { <tr><td colspan="5" class="empty-table">No hay compras registradas para este producto.</td></tr> }</tbody></table></div></div> }
    @if (tab()==='ajustes') { <div class="tab-content"><h3>Control de existencias</h3><p class="muted">Ajusta la cantidad disponible para representar una entrada, venta o corrección.</p>@if (store.role()==='admin') { <div class="adjust-form"><label class="field-label">Nueva cantidad<input class="field-input" type="number" min="0" [(ngModel)]="newQuantity" /></label><button class="btn btn-primary" (click)="adjust(p)">Guardar ajuste</button></div> } @else { <p class="inline-hint">Solo un administrador puede modificar las existencias.</p> }</div> }
    @if (tab()==='historial') { <div class="tab-content"><h3>Actividad del producto</h3><div class="activity-row"><span class="activity-dot"></span><div><strong>Producto disponible en el catálogo</strong><small>Información de demostración</small></div></div><div class="activity-row"><span class="activity-dot"></span><div><strong>Unidades vendidas: {{ p.sold }}</strong><small>Resumen acumulado</small></div></div></div> }
  </section> } @else { <div class="card empty-state">No encontramos este producto. <a routerLink="/inventario">Volver al inventario</a></div> }
  @if (editing()) { <div class="modal-backdrop" (click)="editing.set(false)"><section class="modal-card small-modal" role="dialog" aria-modal="true" aria-label="Editar producto" (click)="$event.stopPropagation()"><div class="modal-header"><h2>Editar producto</h2><button class="icon-button" (click)="editing.set(false)" aria-label="Cerrar"><app-icon name="close"/></button></div><form class="modal-form" (ngSubmit)="saveEdit()"><label class="field-label">Nombre<input class="field-input" name="name" [(ngModel)]="draft.name" required /></label><label class="field-label">Categoría<input class="field-input" name="category" [(ngModel)]="draft.category" required /></label><label class="field-label">Precio de compra (Bs.)<input class="field-input" type="number" min="0" name="price" [(ngModel)]="draft.price" required /></label><label class="field-label">Stock mínimo<input class="field-input" type="number" min="0" name="threshold" [(ngModel)]="draft.threshold" required /></label><div class="modal-actions"><button type="button" class="btn btn-outline" (click)="editing.set(false)">Cancelar</button><button class="btn btn-primary" type="submit">Guardar cambios</button></div></form></section></div> }
` })
export class ProductDetail {
  readonly store=inject(DemoStore); private readonly route=inject(ActivatedRoute);
  readonly money=money; readonly dateLabel=dateLabel; readonly stockStatus=stockStatus;
  readonly tab=signal<'general'|'compras'|'ajustes'|'historial'>('general'); readonly editing=signal(false);
  readonly params=toSignal(this.route.paramMap,{initialValue:this.route.snapshot.paramMap});
  readonly product=computed(()=>this.store.products().find(p=>p.id===this.params().get('id')));
  readonly relatedOrders=computed(()=>this.store.orders().filter(o=>o.product===this.product()?.name));
  newQuantity=0; draft:Product={id:'',name:'',category:'',price:0,quantity:0,threshold:0,unit:'unid.',expiry:'',supplier:'',sold:0};
  constructor(){this.newQuantity=this.product()?.quantity??0;}
  supplierPhone(name:string){return this.store.suppliers().find(s=>s.name===name)?.phone || '—';}
  openEdit(p:Product){this.draft={...p};this.newQuantity=p.quantity;this.editing.set(true);}
  saveEdit(){if(!this.draft.name.trim())return;this.store.updateProduct({...this.draft});this.editing.set(false);}
  adjust(p:Product){if(this.newQuantity<0)return;this.store.updateProduct({...p,quantity:this.newQuantity});}
  download(p:Product){downloadCsv(`producto-${p.id}.csv`,['Código','Nombre','Categoría','Precio Bs.','Cantidad','Stock mínimo'],[[p.id,p.name,p.category,p.price,p.quantity,p.threshold]]);}
}
