import { Component, computed, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DemoStore, money } from '../data/demo-store';
import { Icon } from '../shared/icon';

@Component({selector:'app-reports',standalone:true,imports:[RouterLink,Icon],template:`
  <div class="page-header"><div><div class="eyebrow">ANÁLISIS</div><h1>Reportes</h1><p>Una vista clara del desempeño de tu tienda.</p></div><span class="period-pill page-period">Últimos 6 meses</span></div>
  <div class="reports-grid"><section class="card report-overview"><div class="card-heading"><h2>Resumen financiero</h2></div><div class="report-primary-metrics"><div><strong>{{money(6868)}}</strong><span>Ganancia estimada</span></div><div><strong>{{money(18300)}}</strong><span>Ingresos</span></div><div><strong>{{money(11432)}}</strong><span>Costos</span></div></div><div class="report-secondary-metrics"><div><strong>{{money(stockValue())}}</strong><span>Valor del inventario</span></div><div><strong>{{store.orders().length}}</strong><span>Pedidos</span></div><div><strong>{{store.products().length}}</strong><span>Productos</span></div><div><strong>{{store.suppliers().length}}</strong><span>Proveedores</span></div></div></section>
  <section class="card category-card"><div class="card-heading"><h2>Categorías destacadas</h2><a routerLink="/inventario" class="text-link">Ver inventario <app-icon name="arrow"/></a></div><div class="table-scroll"><table><thead><tr><th>Categoría</th><th>Unidades vendidas</th><th>Participación</th></tr></thead><tbody>@for(c of topCategories();track c.name){<tr><td>{{c.name}}</td><td>{{c.sold}}</td><td>{{c.percent}}%</td></tr>}</tbody></table></div></section>
  <section class="card revenue-chart-card"><div class="card-heading"><h2>Ingresos y ganancias</h2><span class="period-pill">Mensual</span></div><div class="line-chart"><div class="line-y-axis"><span>20 mil</span><span>15 mil</span><span>10 mil</span><span>5 mil</span><span>0</span></div><div class="line-plot"><div class="line-grid"><span></span><span></span><span></span><span></span><span></span></div><svg viewBox="0 0 1000 240" preserveAspectRatio="none" aria-label="Gráfico de ingresos y ganancias"><polyline points="0,178 200,148 400,162 600,85 800,57 1000,92" fill="none" stroke="var(--color-primary)" stroke-width="4" vector-effect="non-scaling-stroke"/><polyline points="0,206 200,181 400,190 600,146 800,115 1000,136" fill="none" stroke="var(--color-chart-secondary)" stroke-width="4" vector-effect="non-scaling-stroke"/><circle cx="800" cy="57" r="7" fill="var(--color-primary)"/></svg><div class="line-x-axis"><span>Abr</span><span>May</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Sep</span></div></div></div><div class="chart-legend"><span><i class="legend-swatch black"></i> Ingresos</span><span><i class="legend-swatch gray"></i> Ganancias</span></div></section>
  <section class="card table-card best-products"><div class="card-heading"><h2>Productos más vendidos</h2><a routerLink="/inventario" class="text-link">Ver todos <app-icon name="arrow"/></a></div><div class="table-scroll"><table><thead><tr><th>Producto</th><th>Código</th><th>Categoría</th><th>Unidades disponibles</th><th>Unidades vendidas</th><th>Valor de ventas</th></tr></thead><tbody>@for(p of topProducts();track p.id){<tr><td><a class="table-primary" [routerLink]="['/inventario',p.id]">{{p.name}}</a></td><td>{{p.id}}</td><td>{{p.category}}</td><td>{{p.quantity}}</td><td>{{p.sold}}</td><td>{{money(p.sold*p.price)}}</td></tr>}</tbody></table></div></section></div>
`})
export class Reports {
  readonly store=inject(DemoStore);readonly money=money;
  readonly stockValue=computed(()=>this.store.products().reduce((n,p)=>n+p.quantity*p.price,0));
  readonly topProducts=computed(()=>[...this.store.products()].sort((a,b)=>b.sold-a.sold).slice(0,5));
  readonly topCategories=computed(()=>{const groups=new Map<string,number>();for(const p of this.store.products())groups.set(p.category,(groups.get(p.category)||0)+p.sold);const total=[...groups.values()].reduce((a,b)=>a+b,0);return [...groups].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name,sold])=>({name,sold,percent:Math.round(sold/total*100)}));});
}
