import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DemoStore, Supplier, downloadCsv } from '../data/demo-store';
import { Icon } from '../shared/icon';

const blankSupplier=():Supplier=>({id:'',name:'',product:'',phone:'',email:'',returns:true,pending:0});
@Component({selector:'app-suppliers',standalone:true,imports:[FormsModule,Icon],template:`
  <div class="page-header"><div><div class="eyebrow">DIRECTORIO</div><h1>Proveedores</h1><p>Organiza los contactos de abastecimiento de tu tienda.</p></div></div>
  <section class="card table-card"><div class="card-heading table-heading"><div><h2>Todos los proveedores</h2><p>{{ filtered().length }} contactos registrados</p></div><div class="card-actions">@if(store.role()==='admin'){<button class="btn btn-primary" (click)="open()"><app-icon name="plus"/> Agregar proveedor</button>}<select class="btn btn-outline filter-select" aria-label="Filtrar por devoluciones" [ngModel]="returnFilter()" (ngModelChange)="returnFilter.set($event)"><option value="">Todos</option><option value="si">Acepta devoluciones</option><option value="no">No acepta devoluciones</option></select><button class="btn btn-outline" (click)="export()"><app-icon name="download"/><span class="hide-small">Descargar</span></button></div></div>
  <div class="table-scroll"><table><thead><tr><th>Proveedor</th><th>Productos</th><th>Teléfono</th><th>Correo electrónico</th><th>Devoluciones</th><th>En camino</th></tr></thead><tbody>@for(s of pageItems();track s.id){<tr><td><span class="table-primary">{{s.name}}</span><small class="table-sub">{{s.id}}</small></td><td>{{s.product}}</td><td>{{s.phone}}</td><td>{{s.email}}</td><td><span class="status" [class.status-good]="s.returns" [class.status-bad]="!s.returns">{{s.returns?'Acepta':'No acepta'}}</span></td><td>{{s.pending || '—'}}</td></tr>} @empty {<tr><td colspan="6" class="empty-table">No encontramos proveedores con ese criterio.</td></tr>}</tbody></table></div><div class="table-footer"><button class="btn btn-outline" [disabled]="page()===1" (click)="page.update(n=>n-1)">Anterior</button><span>Página {{page()}} de {{pageCount()}}</span><button class="btn btn-outline" [disabled]="page()>=pageCount()" (click)="page.update(n=>n+1)">Siguiente</button></div></section>
  @if(modalOpen()){<div class="modal-backdrop" (click)="modalOpen.set(false)"><section class="modal-card" role="dialog" aria-modal="true" aria-label="Nuevo proveedor" (click)="$event.stopPropagation()"><div class="modal-header"><div><div class="eyebrow">DIRECTORIO</div><h2>Nuevo proveedor</h2></div><button class="icon-button" aria-label="Cerrar" (click)="modalOpen.set(false)"><app-icon name="close"/></button></div><form class="modal-form" (ngSubmit)="save()"><div class="form-grid"><label class="field-label">Nombre del proveedor<input class="field-input" name="name" [(ngModel)]="draft.name" required placeholder="Ej. Distribuidora Belleza" /></label><label class="field-label">Producto principal<input class="field-input" name="product" [(ngModel)]="draft.product" required placeholder="Ej. Shampoo" /></label><label class="field-label">Teléfono<input class="field-input" name="phone" [(ngModel)]="draft.phone" required placeholder="Ej. 70123456" /></label><label class="field-label">Correo electrónico<input class="field-input" type="email" name="email" [(ngModel)]="draft.email" placeholder="contacto@ejemplo.bo" /></label><label class="field-label">¿Acepta devoluciones?<select class="field-input" name="returns" [(ngModel)]="draft.returns"><option [ngValue]="true">Sí</option><option [ngValue]="false">No</option></select></label><label class="field-label">Unidades en camino<input class="field-input" type="number" min="0" name="pending" [(ngModel)]="draft.pending" /></label></div>@if(error()){<p class="form-error">{{error()}}</p>}<div class="modal-actions"><button type="button" class="btn btn-outline" (click)="modalOpen.set(false)">Cancelar</button><button type="submit" class="btn btn-primary">Agregar proveedor</button></div></form></section></div>}
`})
export class Suppliers {
  readonly store=inject(DemoStore);readonly modalOpen=signal(false);readonly error=signal('');readonly page=signal(1);readonly returnFilter=signal(''); draft=blankSupplier();
  readonly filtered=computed(()=>this.store.suppliers().filter(s=>`${s.name} ${s.product} ${s.email}`.toLowerCase().includes(this.store.query().toLowerCase())&&(!this.returnFilter()||(this.returnFilter()==='si')===s.returns)));
  readonly pageCount=computed(()=>Math.max(1,Math.ceil(this.filtered().length/8)));
  readonly pageItems=computed(()=>this.filtered().slice((Math.min(this.page(),this.pageCount())-1)*8,Math.min(this.page(),this.pageCount())*8));
  open(){this.draft=blankSupplier();this.error.set('');this.modalOpen.set(true);}
  save(){if(!this.draft.name.trim()||!this.draft.product.trim()||!this.draft.phone.trim()){this.error.set('Completa nombre, producto y teléfono.');return;}this.store.addSupplier({...this.draft,id:`SUP-${String(this.store.suppliers().length+1).padStart(3,'0')}`});this.page.set(1);this.modalOpen.set(false);}
  export(){downloadCsv('proveedores-cabellos-vero.csv',['Proveedor','Producto','Teléfono','Correo','Acepta devoluciones','En camino'],this.filtered().map(s=>[s.name,s.product,s.phone,s.email,s.returns?'Sí':'No',s.pending]));}
}
